config/routes.rb
Rails.application.routes.draw do
  get "pages/welcome"
  get "pages/weather"
  root 'pages#welcome' # Set the first page as the root
  post 'navigate', to: 'pages#welcome', as: 'navigate' # Route for the button submission
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
    if request.post?
      session[:zipcode] = params[:zipcode]
      redirect_to pages_weather_path
    end

  end
  
  def weather
    @zipcode = session[:zipcode]
    require 'net/http'
    require 'json'
    if @zipcode.present?
      @url = "http://api.weatherapi.com/v1/current.json?q=#{@zipcode}&key=887155fa16f441a783d34634251501"
    else
      @url = "http://api.weatherapi.com/v1/current.json?q=43201&key=887155fa16f441a783d34634251501"
    end
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)
    if @output.key?("error")
      @final_output = "Error: " + @output["error"]["message"]
    else
      @final_output = @output
    end
    puts(@final_output)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Weatherapp2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/weather.html.erb
<h1>Weatherapp</h1>
<p>Welcome the weather forecast!</p>
<p>Made by Ryan Liu</p>
<p>PM Accelerator</p>

<% if @final_output.is_a?(Hash) && !@final_output.key?("error") %>
  <p>
    Location: <%= @final_output["location"]["name"] %> <%= @final_output["location"]["region"] %> <br />
    Current time: <%= @final_output["location"]["localtime"] %> <br />
    Type: <%= @final_output["current"]["condition"]["text"] %> <br />
    Temperature (°F): <%= @final_output["current"]["temp_f"] %> <br />
    Wind (mph): <%= @final_output["current"]["wind_mph"] %> <br />
    Precipitation (in): <%= @final_output["current"]["precip_in"] %> <br />
    Cloud Cover: <%= @final_output["current"]["cloud"] %>% <br />
    Feels Like Temp (°F): <%= @final_output["current"]["feelslike_f"] %> <br />
  </p>
<% else %>
  <p><%= @final_output %></p>
<% end %>



<%= link_to "Back to First Page", pages_welcome_path, class: "btn btn-secondary" %>

<%# <p>The ZIP code inputted is: <%= @zipcode %></p>
<%# <p><%= "The ZIP code inputted is: #{h(@zipcode)}" %></p>
<%# <p> Weather: <%= @final_output %></p>

app/views/pages/welcome.html.erb
<h1>Weatherapp</h1>
<p>Fill in a zipcode and submit to retrieve a forecast.</p>
<p>Made by Ryan Liu</p>
<p>PM Accelerator</p>
<p>Description: The Product Manager Accelerator Program is designed to support PM professionals through every stage of their careers. From students looking for entry-level jobs to Directors looking to take on a leadership role, our program has helped over hundreds of students fulfill their career aspirations.
</p>
<%= form_with url: navigate_path, method: :post do %>
  <div class="mb-3">
    <%= label_tag :zipcode, "Enter A Zipcode:" %>
    <%= text_field_tag :zipcode %>
  </div>
  <%= submit_tag "Submit ZIP", class: "btn btn-primary" %>
<% end %>